Repository UTSA-ACM/RowdyHacks2022, pull requests merged in 2022-03, with the labels that each got.

#10 changing sponsors to partners to remove any adblocker issues
  src/app/faq/faq.component.html
  src/app/home/home.component.html
  src/app/location/location.component.html
  src/app/partners/partners.component.html
  src/assets/images/partners/Helping_Here_Blk_Red.jpg
  src/assets/images/partners/Helping_Here_Blk_Red.png
  src/assets/images/partners/acm-logo.svg
  src/assets/images/partners/google-logo.svg
  src/assets/images/partners/heb-logo.svg
  src/assets/images/partners/mitre-logo.svg
  src/assets/images/partners/mlh-logo.svg
  src/assets/images/partners/mlh-trust-badge-2022-white.svg
  src/assets/images/partners/paycom-logo.svg
  src/assets/images/partners/sticker-mule-logo.svg
  src/assets/images/partners/tdsynnex-logo.svg
  src/assets/images/partners/utsa-cos-logo.png
  src/assets/images/partners/utsa-cos.svg
  src/assets/images/partners/utsa-cs-logo.svg
  src/assets/images/partners/utsa-engineering.png
  src/assets/images/partners/valero-logo.svg
  src/styles.sass
Labels: bug

#13 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#14 Security Updates and CronJob
  .github/workflows/codeql-analysis.yml
  package-lock.json
  package.json
Labels: enhancement

#15 Nav bar changes
  src/app/app.component.html
  src/app/app.component.sass
  src/app/partners/partners.component.html
  src/index.html
  src/styles.sass
Labels: bug

#16 Dev
  src/app/app.component.html
  src/app/app.component.sass
  src/app/home/home.component.html
  src/app/partners/partners.component.html
  src/assets/images/mentors/bhavya_gokana.png
  src/assets/images/mentors/people-gal-4.png
  src/assets/images/partners/AssemblyAI_logo.svg
  src/assets/images/partners/cake_logo_blue_gray.svg
  src/assets/images/partners/wolfram.svg
  src/assets/js/jquery-3.6.0.min.js
  src/assets/js/mentors.json
  src/assets/js/script.js
  src/index.html
  src/styles.sass
Labels: enhancement

#17 Updates on the JS and changes to the partner links
  src/app/home/home.component.html
  src/app/partners/partners.component.html
  src/index.html
  src/styles.sass
Labels: bug

#18 Feature/update partner sections
  src/app/home/home.component.html
  src/app/partners/partners.component.html
  src/assets/images/partners/Klesse-COEID.png
  src/assets/images/partners/acm-logo.png
  src/assets/images/partners/cos-scc-logo.png
  src/assets/images/partners/frost.svg
  src/assets/images/partners/makerspace-logo.png
  src/assets/js/partners.json
  src/assets/js/script.js
Labels: enhancement

#20 Feature/hacker schedule
  src/app/schedule/schedule.component.html
  src/assets/js/partners.json
  src/assets/js/schedule.json
  src/assets/js/script.js
  src/assets/js/sundaySchedule
  src/styles.sass
Labels: enhancement

#22 Mentors && Schedule
  src/app/home/home.component.html
  src/app/mentors/mentors.component.html
  src/app/schedule/schedule.component.html
  src/assets/images/mentors/Anna_Arroyo.jpg
  src/assets/images/mentors/Jada_Ebong.jpg
  src/assets/images/mentors/Retro_Manishimwe.jpg
  src/assets/images/mentors/bhavya-gokana.jpg
  src/assets/images/mentors/bhavya_gokana.png
  src/assets/images/mentors/people-gal-4.png
  src/assets/js/mentors.json
  src/assets/js/partners.json
  src/assets/js/schedule.json
  src/assets/js/script.js
  src/assets/js/sundaySchedule
  src/styles.sass
Labels: enhancement

#23 Updated partners
  src/assets/images/partners/google-logo.svg
  src/assets/js/partners.json
Labels: update

#25 Style Update
  src/assets/js/mentors.json
  src/assets/js/schedule.json
  src/assets/js/script.js
  src/styles.sass
Labels: update

#24 Partner Update
  package-lock.json
  package.json
  src/app/app.component.sass
  src/app/schedule/schedule.component.html
  src/assets/images/mentors/people-gal-1.png
  src/assets/images/mentors/people-gal-2.png
  src/assets/images/mentors/people-gal-3.png
  src/assets/images/mentors/people-gal-4.png
  src/assets/images/mentors/people-guy-1.png
  src/assets/images/mentors/people-guy-2.png
  src/assets/images/mentors/people-guy-3.png
  src/assets/images/mentors/people-guy-4.png
  src/assets/images/partners/google-logo.svg
  src/assets/js/mentors.json
  src/assets/js/partners.json
  src/assets/js/schedule.json
  src/assets/js/script.js
  src/assets/js/sundaySchedule
  src/styles.sass
Labels: enhancement, update

#28 Schedule & Mentor Updates
  src/app/faq/faq.component.sass
  src/assets/js/schedule.json
  src/assets/js/script.js
  src/styles.sass
Labels: update
